config/routes.rb
Rails.application.routes.draw do

  resources :recipes
  resources :planners
  root to: 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal.rb
class Meal <ApplicationRecord
  belongs_to :recipe
  belongs_to :planner 
  belongs_to :meal, inverse_of: :meals

  validates :date, presence: true
  validates :planner, presence: true
  validates :recipe, presence: true
end

app/models/planner.rb
class Planner < ApplicationRecord
  belongs_to :user

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :user, presence: true

  has_many :meals, -> { order(:date) }, inverse_of: :planner, dependent: :destroy
  accepts_nested_attributes_for :meals

  def plan_meals
    user_recipe_ids = user.recipes.pluck(:id)

    (start_date..end_date).each do |date|
      available_recipe_ids = user_recipe_ids - meals.map(&:recipe_id)
      meals.build(date: date, recipe_id: available_recipe_ids.sample)
    end
  end

  def to_s
    "#{start_date} - #{end_date}"
  end

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, uniqueness: { scope: :user_id }

  def to_s
    title
  end 
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  has_many :recipes
  has_many :planners

  def recipe_options
    recipes.map do |recipe|
      [recipe.title, recipe.id]
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

  
end

app/controllers/planners_controller.rb
class PlannersController < ApplicationController
  before_action :require_login

  def new
    @planner = current_user.planners.build(start_date: params[:start_date] || Date.today, end_date: params[:end_date] || 6.days.from_now.to_date)
    @planner.plan_meals
  end

  def create
    @planner = current_user.planners.build(planner_params)

    if @planner.save
      redirect_to planner_path(@planner)
    else
      @errors = @planner.errors.full_messages
      render :new
    end
  end

  def show
    @planner = current_user.planners.find(params[:id])
  end

  def index
    @current_planner = current_user.planners.where("start_date <= ? AND end_date >= ?", Date.today, Date.today).first
    @planners = current_user.planners.order("start_date desc")
  end

  def destroy
    @planner = current_user.planners.find(params[:id])
    @planner.destroy
    redirect_to planner_path
  end

  def edit
    @planner = current_user.planners.find(params[:id])
  end

  def update
    @planner = current_user.planners.find(params[:id])

    if @planner.update_attributes(planner_params)
      redirect_to planner_path(@planner)
    else
      @errors = @planner.errors.full_messages
      render :edit
    end 
  end


  private

  def planner_params
    params.require(:planner).permit(:start_date, :end_date, meals_attributes: [:id, :date, :recipe_id])
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :require_login

  def new
    @recipe = current_user.recipes.new
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
      if @recipe.save
      redirect_to recipes_path
    else
      @errors = @recipe.errors.full_messages
      render :new
    end
  end

  def index
    @recipes = Recipe.order(:id)
  end

  def show
    @recipe = current_user.recipes.find(params[:id])
  end

  def edit
    @recipe = current_user.recipes.find(params[:id])
  end

  def update
    @recipe = current_user.recipes.find(params[:id])
    if @recipe.update_attributes(recipe_params)
      redirect_to recipe_path(@recipe), notice: 'Recipe Updated!'
    else
      @errors = @recipe.errors.full_messages
      render :edit
    end
  end 


  def destroy
    @recipe = current_user.recipes.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path, notice: 'Deleted Recipe #{recipe.title}'
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/planners_helper.rb
module PlannersHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg fixed-top">
  <a class="navbar-brand" href="#">Figure Out</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="nav navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to 'HOME', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">RECIPES</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">LISTS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">MORE</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FigureOut</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if signed_in? %>
        Signed in as: <%= current_user.email %>
        <%= button_to 'Sign out', sign_out_path, method: :delete %>
      <% else %>
        <%= link_to 'Sign in', sign_in_path %>
      <% end %>
    </header>
    <%= render 'layouts/navigation' %>
    
    <section>

      <div id="flash">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
      </div>
    <%= yield %>
  </section>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/index.html.erb
<div class="container-main">

  <h1>Welcome</h1>
</div>

app/views/planners/_form.html.erb
<%= render 'shared/errors' %>


<%= form_for @planner do |f| %>
  <%= f.hidden_field :start_date %>
  <%= f.hidden_field :end_date %>

  <div class="planners">
    <%= f.fields_for :meals do |meal_fields| %>
    <div class="planner">
      <%= meal_fields.hidden_field :id %>
      <%= meal_fields.hidden_field :date %>
      <p><%= meal_fields.object.date.to_s %></p>
      <div class="form-control">
        <%= meal_fields.label :recipe_id %>
        <%= meal_fields.select :recipe_id, current_user.recipe_options %>
      </div>
    </div>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/planners/edit.html.erb
<h1>Edit your Plan: <%= @planner %></h1>

<%= render 'form' %>

app/views/planners/index.html.erb
<h1>Plans</h1>

<% if @current_planner.present? %>
<h3>Current Plan</h3>

<div>
  <ul class="planners">
    <% @current_planner.meals.each do |meal| %>
      <li class="planner">
        <%= meal.date %> - <%= link_to meal.recipe.to_s, recipe_path(meal.recipe) %>
      </li>
      <% end %>
    </ul>
  </div>
<% end %>

<h3>All Your Plans</h3>

<% @planners.each do |planner| %>
  <div class="planner">
    <%= link_to planner, planner_path(planner) %>
  </div>
<% end %>

<div class="actions">
  <%= link_to "Fresh Plan", new_planner_path %>
</div>

app/views/planners/new.html.erb
<h1>Let's Plan Our Menu</h1>

<%= form_for @planner, url: new_planner_path, method: 'GET' do |f| %>
  <div class="form-control">
    <%= f.label :start_date %>
    <%= f.text_field :start_date, type: "date" %>
  </div>

  <div class="form-control">
    <%= f.label :end_date %>
    <%= f.text_field :end_date, type: 'date' %>
  </div>

  <div class="actions">
    <%= f.submit "What's for dinner?" %>
  </div>
<% end %>

<%= render 'form' %>

app/views/planners/show.html.erb
<h1>Here is the Meal Plan: <%= @planner %></h1>

<h2>Meals</h2>

<ul class="planners">
  <% @planner.meals.each do |meal| %>
    <li class="planner">
      <%= meal.date %> - <%= link_to meal.recipe, recipe_path(meal.recipe) %>
    </li>
  <% end %>
</ul>

<div class="actions">
  <ul class="recipe-actions">
    <li>
      <%= link_to 'Edit your Plan', edit_planner_path(@planner) %>
    </li>
    <li>
      <%= link_to 'Delete your Plan', planner_path(@planner), data: { confirm: 'Are you positive you want to delete this plan?' }, method: :delete %>
    </li>
  </ul>
</div>

app/views/recipes/_form.html.erb
<%= render 'shared/errors' %>

<%= form_for(@recipe) do |f| %>
  <div class="form-group">
    <%= f.text_field :title, class: 'form-control' %></br>
  </div>
  <div class="form-group">
    <%= f.text_area :description, class: 'form-control' %></br>
  </div>
  <div class="actions">
    <%= f.submit 'Add Recipe', class: 'btn btn-primary' %>
  </div>
  <% end %>

app/views/recipes/edit.html.erb
<h2>Edit your Recipe</h2>

<%= render 'form' %>

app/views/recipes/index.html.erb
  <div id="recipes">
    <% @recipes.each do |recipe| %>
    <div class="recipe">
      <h3><%= recipe.title %></h3></br>
      <p><%= recipe.description %></p></br>
    
      <ul class="recipe-actions">
        <li><%= link_to 'Edit', edit_recipe_path(recipe) %></li>
        <li><%= link_to 'Delete', recipe_path(recipe), data: { confirm: 'Are you sure you want to delete: #{recipe.title}?' }, method: :delete %></li>
      </div>
    </div>
  <% end %>

app/views/recipes/new.html.erb
<h3 class="text-center recipe-form">Add Your Recipe</h3>

<%= render 'form' %>

app/views/recipes/show.html.erb
<h2><%= @recipe.title %></h2>

<h3>description: </h3>
<p><%= @recipe.description %></p>

<div>
  <ul class="recipes-links">
    <li><%= link_to 'back', recipes_path %></li>
    <li><%= link_to 'edit', edit_recipe_path(@recipe) %></li>
    <li><%= link_to 'delete', recipe_path(@recipe), data: { confirm: 'Are you sure you want to delete: #{@recipe.title}?' }, method: :delete %></li>
  </ul>
</div>

app/views/shared/_errors.html.erb
<% if @errors.present? %>
<div class="errors">
  <ul>
    <% @errors.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
</div>
<% end %>